AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  DDBTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "CandidateUUID"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "CandidateUUID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      timeout: 30 # optional, in seconds, default is 6
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        WaitEvent:
          Type: Api
          Properties:
            Path: /wait
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post
        GetAll:
          Type: Api
          Properties:
            Path: /simpsons
            Method: get
        GetOne:
          Type: Api
          Properties:
            Path: /simpsons/{id}
            Method: get
        GetQuote:
          Type: Api
          Properties:
            Path: /simpsons/{id}/phrases
            Method: get
